CREATE TABLE KH_STUDENT(
STD_NO NUMBER PRIMARY KEY,
STD_NAME NVARCHAR2(5) NOT NULL,
STD_AGE NUMBER NOT NULL,
MAJOR NVARCHAR2(10) NOT NULL,
SCORE NUMBER NOT NULL,
GENDER NVARCHAR2(3) NOT NULL,
CLUB NVARCHAR2(20) NOT NULL,
ENT_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN KH_STUDENT.STD_NO 			IS '학번';
COMMENT ON COLUMN KH_STUDENT.STD_NAME			IS '이름';
COMMENT ON COLUMN KH_STUDENT.STD_AGE 			IS '나이';
COMMENT ON COLUMN KH_STUDENT.MAJOR 				IS '전공';
COMMENT ON COLUMN KH_STUDENT.SCORE	 			IS '점수';
COMMENT ON COLUMN KH_STUDENT.GENDER 			IS '성별';
COMMENT ON COLUMN KH_STUDENT.CLUB 				IS '동아리';
COMMENT ON COLUMN KH_STUDENT.ENT_DATE			IS '입학일자';

CREATE SEQUENCE SEQ_STD_NO NOCACHE;

INSERT INTO KH_STUDENT VALUES(SEQ_STD_NO.NEXTVAL, '정숙', 21, '심리학', 62, '여', '농구부', SYSDATE);
INSERT INTO KH_STUDENT VALUES(SEQ_STD_NO.NEXTVAL, '현숙', 23, '경영학', 83, '여', '사진부', SYSDATE);
INSERT INTO KH_STUDENT VALUES(SEQ_STD_NO.NEXTVAL, '옥순', 25, '물리학', 59, '여', '제빵부', SYSDATE);
INSERT INTO KH_STUDENT VALUES(SEQ_STD_NO.NEXTVAL, '영숙', 22, '심리학', 88, '여', '사진부', SYSDATE);
INSERT INTO KH_STUDENT VALUES(SEQ_STD_NO.NEXTVAL, '순자', 20, '국문학', 99, '여', '제빵부', SYSDATE);
INSERT INTO KH_STUDENT VALUES(SEQ_STD_NO.NEXTVAL, '정희', 26, '국문학', 36, '여', '밴드부', SYSDATE);

INSERT INTO KH_STUDENT VALUES(SEQ_STD_NO.NEXTVAL, '영철', 25, '경영학', 87, '남', '제빵부', SYSDATE);
INSERT INTO KH_STUDENT VALUES(SEQ_STD_NO.NEXTVAL, '상철', 21, '물리학', 56, '남', '밴드부', SYSDATE);
INSERT INTO KH_STUDENT VALUES(SEQ_STD_NO.NEXTVAL, '영호', 20, '물리학', 76, '남', '농구부', SYSDATE);
INSERT INTO KH_STUDENT VALUES(SEQ_STD_NO.NEXTVAL, '영식', 22, '심리학', 49, '남', '사진부', SYSDATE);
INSERT INTO KH_STUDENT VALUES(SEQ_STD_NO.NEXTVAL, '경수', 26, '국문학', 98, '남', '제빵부', SYSDATE);
INSERT INTO KH_STUDENT VALUES(SEQ_STD_NO.NEXTVAL, '광수', 23, '경영학', 66, '남', '농구부', SYSDATE);

------------------------------------------------------------------------------------------------------

SELECT * FROM KH_STUDENT;
COMMIT;

SELECT M.STD_NAME
FROM KH_STUDENT M
WHERE M.MAJOR = '심리학'
AND M.CLUB = '농구부'
AND M.SCORE <= (SELECT M1.SCORE FROM KH_STUDENT M1 WHERE M1.STD_NAME = '영철')
AND M.STD_AGE <= (SELECT M1.STD_AGE FROM KH_STUDENT M1 WHERE M1.STD_NAME = '영철')
AND M.GENDER != '남';

